library(lattice)
library(car)
library(EnvStats)
library(corrplot)
library(ggbiplot)
library(mice)
library(VIM)
library(MASS)
library(Amelia) 
library(ggplot2)
library(tidyr)
library(mlbench)
library(reshape2)
library(dplyrAssist)

source("https://github.com/tidyverse/dplyr")
##1
##1.a
data("Glass") # To load Glass dataframe.
head(Glass)
Glass = Glass[1:9]
d = melt(Glass)
ggplot(d,aes(x = value)) +facet_wrap(~variable,scales = "free_x") + geom_histogram()
ggplot(d,aes(x = variable,y = value)) + facet_wrap(~variable, scale="free") + geom_boxplot()
#From the above plots RI, Na, Ca seems rightly skewed whereas Ba,Mg are left skewed. Few predictors follow normal distribution if we deal with outliers. Mg, Ba, Fe,K,Ca have many outliers compared to other predictors

##1.b.i
# .1 has been added to make all the values positive
symbox(Glass$Al+.1,data=Glass,powers=c(3,2,1,0,-0.5,-1,-2,6.300777),ylab="Aluminium") #To assess which power makes Glass$Al more symmetric.
symbox(Glass$Si+.1,data=Glass,powers=c(3,2,1,0.01485945,0,-0.5,-1,-2),ylab="Silicon") #To assess which power makes Glass$Si more symmetric.
symbox(Glass$Ca+.1,data=Glass,powers=c(3,2,1,0,-0.5,-1,-2),ylab="Calcium") #To assess which power makes Glass$Ca more symmetric.

##1.b.ii
EnvStats::boxcox(Glass$Ca,optimize = TRUE, lambda=c(-5,7)) # To determine optimal value of Glass$Ca by boxcox method
EnvStats::boxcox(Glass$Si,optimize = TRUE, lambda=c(-5,7)) # To determine optimal value of Glass$Si by boxcox method
EnvStats::boxcox(Glass$Al,optimize = TRUE, lambda=c(-5,7)) # To determine optimal value of Glass$Al by boxcox method

##1.c
data("Glass")
Glass = as.data.frame(apply(Glass,2, as.numeric)) # Converting Type variable to numeric.
cormat = cor(Glass)
corrplot(cormat, method = "color")
eig_glass = eigen(cormat)
glasss_pca = prcomp(Glass, scale = T) # Principal component analysis with correlation
summary(glasss_pca)
ggbiplot(glasss_pca)
screeplot(glasss_pca, type = "line", npcs = 10, main = "Scree Plot") # Elbow curve to predict significant principal components

##1.d
plot(Glass[,-10], col = Glass$Type, pch = Glass$Type)
glass.lda = lda(Type ~ RI+Na+Mg+Al+Si+K+Ca+Ba+Fe, data = Glass) # performing LDA considering Type as dependent variable and other variables are dependent in Glass data frame
glass.lda.predict = predict(glass.lda, newdata = Glass[,-11])$class # To predict data.
glass.lda.predict 
ldatable = table(glass.lda.predict,Glass$Type) # creating table with 2 variables.
accuracy <- sum(diag(ldatable))/ sum(ldatable)* 100 
glass.lda$counts

##2
##2.a
data(freetrade) #Loads freetrade dataframe.
dflistwise = freetrade # Creating dataframe dflistwise equal to freetrade.
datawithoutmiss = na.omit(dflistwise) # This function removes complete row if any NA found in that row.
outputa = lm(data=datawithoutmiss,tariff~ year+country+polity+pop+gdp.pc+intresmi+signed+fiveop+usheg)# Performing regression of datawithoutmiss(pairwise deletion).
summary(outputa)# summary of outputa

##2.b
data(freetrade)
dfMean = freetrade # Creating dataframe dfMean equal to freetrade.
dfMean$tariff[which(is.na(dfMean$tariff))] = mean(dfMean$tariff,na.rm=T)# Mean Imputation.
outputb = lm(data=dfMean,tariff~ year+country+polity+pop+gdp.pc+intresmi+signed+fiveop+usheg) # Performing regression on dfMean
summary(outputb) # Summary of outputb

##2.c
data("freetrade")
library(mice)
dfMice = freetrade # Creating dataframe dfMice equal to freetrade.
imp = mice(dfMice,m=6,meth="mean",maxit = 10) #Applied Multivariate Imputation by Chained Equations with 6 multiple imputations by using "mean" method with 10 maximum iterations. 
fitc = with(imp,lm(tariff~ year+country+polity+pop+gdp.pc+intresmi+signed+fiveop+usheg)) # regression applied.
summary(fitc) # Summary of fitc
est = pool(fitc) # pools the results generated by repeated data analysis.
summary(est) # Summary of est.

##4
##4.a
crime_data = read.csv("crime.csv", header = T, stringsAsFactors = F) #Read the crime.csv file

##4.b
summary(crime_data) #Display the data summary 
colnames(crime_data) #Display the colom names in the dataframe
nrow(crime_data) #Number of rows in the data frame
ncol(crime_data) #Number of colomns inn the data frame
crime_homicide = crime_data[grepl("Homicide", crime_data$Text_General_Code, ignore.case = T),] #Extract all Homicide rows
crime_rape = crime_data[crime_data$Text_General_Code == "Rape",] #Extract all Rape rows
#To detect the outliers with label
source("https://raw.githubusercontent.com/talgalili/R-code-snippets/master/boxplot.with.outlier.label.r")
#crimes frequency based in hour of day (24 hours time)
par(mfrow = c(1,2))
boxplot.with.outlier.label(crime_homicide$Hour,ylab = "reported hour in a day", xlab = "Homicide frequency")
boxplot.with.outlier.label(crime_rape$Hour,ylab = "reported hour in a day", xlab = "Rape frequency")
par(mfrow = c(1,2))
a = ggplot(crime_homicide, aes(x=Hour)) + geom_histogram(aes(y=..density..),binwidth= 3,colour="green", fill="red") +geom_density(alpha=0.6, fill="blue")
a + labs(title = "For Homicide Crime")
b = ggplot(crime_rape, aes(x=Hour)) + geom_histogram(aes(y=..density..),binwidth= 3,colour="green", fill="red") +geom_density(alpha=0.6, fill="blue")
b + labs(title = "For Rape Crime")
#Missingness of data
apply(crime_data,2, function(x){table(is.na(x))})


##3
##3a
housingData = read.csv("housingData.csv", header = TRUE, sep = ",") # Loading housing data
aggr(housingData)
summary(housingData)
#from the summary of the data we can say that few columns have missing values and those missing values can be categeroized among categorical and numerical values
#The missing values indicate that majority of the houses do not have alley access, no pool, no fence and no elevator, 2nd garage, shed or tennis court that is covered by the MiscFeature.
cateogerical_var = names(housingData)[which(sapply(housingData, is.character))]
numerical_var = names(housingData)[which(sapply(housingData, is.numeric))]
colSums(sapply(housingData, is.na))
#The numeric variables do not have as many missing values as cateogerical, but there are still some present. There are 259 values for the LotFrontage, 8 missing values for MasVnrArea and 81 missing values for GarageYrBlt.  
#Correlation between the numeric attributes
housing_cor_numerics = cor(na.omit(housingData[,numerical_var]))
corrplot:: corrplot(housing_cor_numerics, method="circle", type="lower", insig = "blank")
housing_missing_var = names(housingData)[which(colSums(sapply(housingData, is.na)) > 0)]
aggr(housingData, col=c('navyblue','red'), numbers=TRUE, sortVars=TRUE, labels=names(housingData), cex.axis=.6, gap=4, ylab=c("Histogram of missing data","Pattern"))
#Now we will look at the meanprice distribution by neighborhood, from the plot the mean price of the sales price is hoigh in noridge and Nridght neighbours(costly areas might be)
housingData %>% group_by(Neighborhood) %>% summarize(mean_price = mean(SalePrice)) %>% arrange(desc(mean_price)) %>% ggplot(aes(x = Neighborhood, y = mean_price))+geom_bar(stat = "identity", fill='red', alpha=0.7)+ggtitle('Average Sale Price by Neighborhood')+theme(axis.text.x = element_text(angle = 60))
#Explore Sales Price
ggplot(data=housingData, aes(x=SalePrice)) + geom_histogram(color='white', alpha=0.5, fill='blue') +scale_x_continuous(limits = c(min(housingData$SalePrice),max(housingData$SalePrice))) +ggtitle('Distribution of Sale Price')
#Distribution of sales price by Neighborhood
ggplot(housingData, aes(x=Neighborhood, y=SalePrice)) +geom_jitter(color='red', width=0.7) +geom_violin(fill='blue', alpha=0.6) +ggtitle('Distribution of Sale Price by Neighborhood') +scale_y_continuous(limits = c(min(housingData$SalePrice),max(housingData$SalePrice))) + theme(axis.text.x=element_text(angle=45, hjust=1))


##3.b
# Feature Engineering
housingData$YearsUsed = housingData$YearBuilt - housingData$YrSold # Sale price depends on the number of years house used, rather than Yearbuilt and YearSold.
housingData$TotalFullBath = housingData$BsmtFullBath - housingData$FullBath # Gives total number of fullBath rooms
housingData$Floorsqft = housingData$X1stFlrSF + housingData$X2ndFlrSF # Gives total Floor area.
housingData$overall = housingData$OverallQual + housingData$OverallCond # summing overall qual & OverallCond
